##
# Update the DNF package cache and install packages as a root user
##
- name: Install required packages
  dnf: name={{item}} state=latest
  become: yes
  with_items:
    - vim
    - fail2ban
    - python3
    - python3-devel
    - python3-virtualenv
    - python3-wheel
    - python3-pip
    - python3-setuptools
    - gcc